services:
  - type: web
    name: orchestrator
    env: docker
    plan: free
    region: oregon
    repo: https://github.com/Debbatisudheer/afe-mos
    branch: main
    dockerfilePath: services/orchestrator/Dockerfile
    buildCommand: ""
    startCommand: ""

  - type: web
    name: vitals-monitor
    env: docker
    plan: free
    region: oregon
    repo: https://github.com/Debbatisudheer/afe-mos
    branch: main
    dockerfilePath: services/agents/healthcare/vitals-monitor/Dockerfile
    buildCommand: ""
    startCommand: ""
